function eye4DLCresnet50eyemoveFeb15shuffle1700000filtered = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   EYE4DLCRESNET50EYEMOVEFEB15SHUFFLE1700000FILTERED =
%   IMPORTFILE(FILENAME) Reads data from text file FILENAME for the default
%   selection.
%
%   EYE4DLCRESNET50EYEMOVEFEB15SHUFFLE1700000FILTERED =
%   IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   eye4DLCresnet50eyemoveFeb15shuffle1700000filtered = importfile('eye4DLC_resnet50_eye_moveFeb15shuffle1_700000filtered.csv', 4, 159022);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2020/03/10 19:45:32

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 4;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
%   column25: double (%f)
%	column26: double (%f)
%   column27: double (%f)
%	column28: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
eye4DLCresnet50eyemoveFeb15shuffle1700000filtered = table(dataArray{1:end-1}, 'VariableNames', {'scorer','DLC_resnet50_eye_moveFeb15shuffle1_700000','DLC_resnet50_eye_moveFeb15shuffle1_1','DLC_resnet50_eye_moveFeb15shuffle1_2','DLC_resnet50_eye_moveFeb15shuffle1_3','DLC_resnet50_eye_moveFeb15shuffle1_4','DLC_resnet50_eye_moveFeb15shuffle1_5','DLC_resnet50_eye_moveFeb15shuffle1_6','DLC_resnet50_eye_moveFeb15shuffle1_7','DLC_resnet50_eye_moveFeb15shuffle1_8','DLC_resnet50_eye_moveFeb15shuffle1_9','DLC_resnet50_eye_moveFeb15shuffle1_10','DLC_resnet50_eye_moveFeb15shuffle1_11','DLC_resnet50_eye_moveFeb15shuffle1_12','DLC_resnet50_eye_moveFeb15shuffle1_13','DLC_resnet50_eye_moveFeb15shuffle1_14','DLC_resnet50_eye_moveFeb15shuffle1_15','DLC_resnet50_eye_moveFeb15shuffle1_16','DLC_resnet50_eye_moveFeb15shuffle1_17','DLC_resnet50_eye_moveFeb15shuffle1_18','DLC_resnet50_eye_moveFeb15shuffle1_19','DLC_resnet50_eye_moveFeb15shuffle1_20','DLC_resnet50_eye_moveFeb15shuffle1_21','DLC_resnet50_eye_moveFeb15shuffle1_22','DLC_resnet50_eye_moveFeb15shuffle1_23','DLC_resnet50_eye_moveFeb15shuffle1_24','DLC_resnet50_eye_moveFeb15shuffle1_25','DLC_resnet50_eye_moveFeb15shuffle1_26'});

